# Site Configuration
repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2

# Personal Info
name: Zachary Choffin
title: Graduate Research Assistant and Ph.D. Candidate
email: zmchoffin@crimson.ua.edu
website: https://www.linkedin.com/in/zchoffin/

# Settings
darkmode: false
github_username: Zchoffin
linkedin_username: zchoffin
orcid_username: 0000-0002-0395-6230

# About Section
about_profile_image: images/profile.jfif
about_content: |
  Hi, my name is Zachary Choffin and I'm a Ph.D Candidate at the Advanced Antenna and Sensor Laboratory at The University of Alabama
  I am most skilled in: <mark>Python</mark> and <mark>Deep Learning</mark>

# Education Section
content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: The University of Alabama, Tuscaloosa
        caption: 2016 - 2020
        sub_title: BSEE
        quote: >
          Established in 1820 and opened to students in 1831, the University of Alabama is the oldest and largest of the public universities in Alabama as well as the University of Alabama System. It is classified among "R1: Doctoral Universities".
        description: |
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

# Publications Section
  - title: Publications
    layout: text
    content: |
      My research has been published in various journals. Here are some of my key publications:
      - Lee, Martin Wooseop, et al. "A Compact Ultra-Wideband Monocone Antenna with Folded Shorting Wires for Vehicle-to-Everything (V2X) Applications." Sensors 23.13 (2023): 6086.
      - Choffin, Zachary, et al. "Lower Body Joint Angle Prediction Using Machine Learning and Applied Biomechanical Inverse Dynamics." Sensors 23.1 (2022): 228.
      - Anderson, Wolfe, et al. "Empirical study on human movement classification using insole footwear sensor system and machine learning." Sensors 22.7 (2022): 2743.
      - Garvin, J., Abushakra, F., Choffin, Z., Shiver, B., Gan, Y., Kong, L., & Jeong, N. (2023). Microwave imaging for watermelon maturity determination. Current Research in Food Science, 6, 100412.
      - Choffin, Z., Jeong, N., Callihan, M., Olmstead, S., Sazonov, E., Thakral, S., ... & Lombardi, V. (2021). Ankle Angle Prediction Using a Footwear Pressure Sensor and a Machine Learning Technique. Sensors, 21(11), 3790.
